name: CoReLG
version: 1.20
date: 2014-12-02
description: |
    Computation with real Lie groups

authors:
    - name: Heiko Dietrich
      url: http://users.monash.edu.au/~heikod/
    - name: Paolo Faccin
      url: mailto:faccin@science.unitn.it
    - name: Willem Adriaan de Graaf
      url: http://www.science.unitn.it/~degraaf

maintainers:
    - name: Heiko Dietrich
      url: http://users.monash.edu.au/~heikod/
    - name: Paolo Faccin
      url: mailto:faccin@science.unitn.it
    - name: Willem Adriaan de Graaf
      url: http://www.science.unitn.it/~degraaf

GAP: ">=4.8"

needed-pkgs:
    - name: "sla"
      version: ">=1.5"
      url: "http://www.science.unitn.it/~degraaf/sla.html"

www: https://gap-packages.github.io/corelg/
readme: README.md
packageinfo: https://gap-packages.github.io/corelg/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/corelg/releases/download/v1.20/corelg-1.20.tar.gz

abstract: |
    The package <span class="pkgname">CoReLG</span> contains                  functionality for working with real semisimple Lie algebras.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    real Lie algebras, nilpotent orbits Cartan subalgebras.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>DFG14</span>]   <b class='BibAuthor'>Dietrich, H., Faccin, P. and de Graaf, W. A.</b>,
     <i class='BibTitle'>CoReLG, Computation with real Lie groups,
             Version 1.20</i>
     (<span class='BibYear'>2014</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/corelg/">https://gap-packages.github.io/corelg/</a></span>.
    </p>
    

bibtex: |
    @misc{ CoReLG1.20,
      author =           {Dietrich, H. and Faccin, P. and de Graaf, W. A.},
      title =            {{CoReLG}, Computation with real Lie groups, {V}ersion 1.20},
      month =            {Dec},
      year =             {2014},
      note =             {Refereed GAP package},
      howpublished =     {\href {https://gap-packages.github.io/corelg/} {\texttt{https://gap-packages.github.io/}\discretionary {}{}{}\texttt{corelg/}}},
      keywords =         {real Lie algebras; nilpotent orbits Cartan subalgebras},
      printedkey =       {DFG14}
    }

