name: CoReLG
version: 1.52
date: 2019-09-30
description: |
    Computing with real Lie algebras

authors:
    - name: Heiko Dietrich
      url: http://users.monash.edu.au/~heikod/
    - name: Paolo Faccin
      url: mailto:paolofaccin86@gmail.com
    - name: Willem de Graaf
      url: http://www.science.unitn.it/~degraaf

maintainers:
    - name: Heiko Dietrich
      url: http://users.monash.edu.au/~heikod/
    - name: Paolo Faccin
      url: mailto:paolofaccin86@gmail.com
    - name: Willem de Graaf
      url: http://www.science.unitn.it/~degraaf

GAP: ">=4.8"

needed-pkgs:
    - name: "sla"
      version: ">=1.5"
      url: "https://gap-packages.github.io/sla/"

www: https://gap-packages.github.io/corelg/
readme: README.md
packageinfo: https://gap-packages.github.io/corelg/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/corelg/releases/download/v1.52/corelg-1.52.tar.gz

abstract: |
    The package <span class="pkgname">CoReLG</span> contains functionality for working with real semisimple Lie algebras.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    real Lie algebras, nilpotent orbits Cartan subalgebras.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>DFG19</span>]   <b class='BibAuthor'>Dietrich, H., Faccin, P. and de Graaf, W.</b>,
     <i class='BibTitle'>CoReLG, Computing with real Lie algebras,
             Version 1.52</i>
     (<span class='BibYear'>2019</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/corelg/">https://gap-packages.github.io/corelg/</a></span>.
    </p>
    

bibtex: |
    @misc{ CoReLG1.52,
      author =           {Dietrich, H. and Faccin, P. and de Graaf, W.},
      title =            {{CoReLG},  Computing with real Lie algebras, {V}ersion
                          1.52},
      month =            {Sep},
      year =             {2019},
      note =             {Refereed GAP package},
      howpublished =     {\href         {https://gap-packages.github.io/corelg/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{corelg/}}},
      keywords =         {real Lie algebras; nilpotent orbits Cartan subalgebras},
      printedkey =       {DFG19}
    }

